
// ==========================================
// CREATION FEATURES (Laws 151-160)
// ==========================================

// 151. Component Scaffold
app.post('/api/create/component', async (req, res) => {
    const { versionId, name } = req.body;
    const targetDir = path.join(LABS_DIR, versionId, 'src', 'components');
    await fs.ensureDir(targetDir);

    const content = `
import React from 'react';

export const ${name} = () => {
    return (
        <div className="${name.toLowerCase()}-container">
            <h1>${name} Component</h1>
            <p>Generated by F.I.G.M.A. Lab</p>
        </div>
    );
};
`;
    await fs.writeFile(path.join(targetDir, `${name}.tsx`), content.trim());
    res.json({ success: true, path: path.join(targetDir, `${name}.tsx`) });
});

// 152. Route Scaffold (Mock injection, real injection is dangerous hot)
app.post('/api/create/route', async (req, res) => {
    const { versionId, routeName } = req.body;
    const routesDir = path.join(LABS_DIR, versionId, 'routes');
    await fs.ensureDir(routesDir);

    const content = `
// Route: ${routeName}
module.exports = (app) => {
    app.get('/${routeName}', (req, res) => {
        res.json({ message: 'Dynamic Route Active' });
    });
};
`;
    await fs.writeFile(path.join(routesDir, `${routeName}.js`), content.trim());
    res.json({ success: true, generated: true });
});

// 153. Config Synth
app.post('/api/create/config', async (req, res) => {
    const { versionId, params } = req.body;
    const configPath = path.join(LABS_DIR, versionId, 'config.json');
    await fs.writeJson(configPath, params || { generated: true }, { spaces: 2 });
    res.json({ success: true, file: configPath });
});

// 154. Readme Gen
app.post('/api/create/readme', async (req, res) => {
    const { versionId } = req.body;
    const p = path.join(LABS_DIR, versionId);
    const pkgPath = path.join(p, 'package.json');

    let pkg = { name: versionId, description: 'No description' };
    if (fs.existsSync(pkgPath)) pkg = await fs.readJson(pkgPath);

    const content = `
# ${pkg.name}

${pkg.description}

## Installation
\`npm install\`

## Usage
\`npm start\`

*Generated on ${new Date().toISOString()}*
`;
    await fs.writeFile(path.join(p, 'README.md'), content.trim());
    res.json({ success: true });
});

// 155. License Stamp
app.post('/api/create/license-stamp', async (req, res) => {
    const { versionId } = req.body;
    const p = path.join(LABS_DIR, versionId);
    if (!fs.existsSync(p)) return res.status(404).json({ error: 'Not found' });

    const LICENSE = "// LICENSE: MIT. Property of User.\n";

    // Recursive walker
    async function walk(dir) {
        const files = await fs.readdir(dir);
        for (const f of files) {
            const fp = path.join(dir, f);
            const stat = await fs.stat(fp);
            if (stat.isDirectory()) {
                if (f !== 'node_modules') await walk(fp);
            } else if (f.endsWith('.js')) {
                const c = await fs.readFile(fp, 'utf-8');
                if (!c.startsWith('// LICENSE')) {
                    await fs.writeFile(fp, LICENSE + c);
                }
            }
        }
    }
    await walk(p);
    res.json({ success: true });
});

// 156. Template Clone (Using Mock Template)
app.post('/api/create/from-template', async (req, res) => {
    const { templateId, newId } = req.body;
    // We assume templates are in _Templates folder or we just create a valid React structure on fly
    const dest = path.join(LABS_DIR, newId);
    await fs.ensureDir(dest);

    // Scaffolding Basic React
    await fs.ensureDir(path.join(dest, 'src'));
    await fs.writeJson(path.join(dest, 'package.json'), { name: newId, version: "0.1.0", dependencies: { "react": "^18.0.0" } });
    await fs.writeFile(path.join(dest, 'src', 'index.js'), "console.log('React App');");

    broadcastState();
    res.json({ success: true, id: newId });
});

// 157. Manifesto Synth
app.post('/api/create/manifesto', async (req, res) => {
    const masterPath = path.join(LABS_DIR, 'Master_Dirty.md');
    let content = "# Master Dirty Log\n\n";

    const dirs = await fs.readdir(LABS_DIR);
    for (const d of dirs) {
        if (d.startsWith('.')) continue;
        const dirty = path.join(LABS_DIR, d, 'dirty.txt');
        if (fs.existsSync(dirty)) {
            const txt = await fs.readFile(dirty, 'utf-8');
            content += `## ${d}\n${txt}\n---\n`;
        }
    }
    await fs.writeFile(masterPath, content);
    res.json({ success: true, file: masterPath });
});

// 158. API Key Gen
const crypto = require('crypto');
app.post('/api/create/apikey', async (req, res) => {
    const key = 'sk-live-' + crypto.randomBytes(16).toString('hex');
    const keyPath = path.join(LABS_DIR, 'secrets.json');
    let db = {};
    if (fs.existsSync(keyPath)) db = await fs.readJson(keyPath);
    db[Date.now()] = key;
    await fs.writeJson(keyPath, db);
    res.json({ key }); // Return only once
});

// 159. Theme Gen
app.post('/api/create/theme', async (req, res) => {
    const name = req.body.name || 'generated_theme';
    const theme = {
        name,
        colors: {
            primary: `hsl(${Math.random() * 360}, 70%, 50%)`,
            background: `hsl(220, 15%, 10%)`,
            text: `hsl(0, 0%, 95%)`
        }
    };
    const p = path.join(LABS_DIR, `${name}.json`);
    await fs.writeJson(p, theme, { spaces: 2 });
    res.json({ success: true, theme });
});

// 160. Project Init
app.post('/api/create/structure', async (req, res) => {
    const { versionId, structure } = req.body; // structure = ['src/api', 'src/utils']
    const root = path.join(LABS_DIR, versionId);

    const created = [];
    if (Array.isArray(structure)) {
        for (const dir of structure) {
            const p = path.join(root, dir);
            await fs.ensureDir(p);
            created.push(dir);
        }
    }
    res.json({ success: true, created });
});
