@echo off
:: ============================================================
:: Vultr Object Storage Configuration
:: Configure your S3 credentials for cloud backups
:: ============================================================
title Configure Object Storage
color 0B

echo.
echo  ========================================
echo    CONFIGURAR OBJECT STORAGE (VULTR S3)
echo  ========================================
echo.
echo Para usar Cloud Backup necesitas credenciales de Vultr S3.
echo Si no tienes una cuenta, puedes crearla en:
echo https://www.vultr.com/products/object-storage/
echo.

set /p VULTR_ACCESS_KEY="Access Key: "
set /p VULTR_SECRET_KEY="Secret Key: "
set /p VULTR_BUCKET_NAME="Bucket Name (default: lab-backups): "
set /p VULTR_ENDPOINT="Endpoint (default: ewr1.vultrobjects.com): "

:: Set defaults if empty
if "%VULTR_BUCKET_NAME%"=="" set "VULTR_BUCKET_NAME=lab-backups"
if "%VULTR_ENDPOINT%"=="" set "VULTR_ENDPOINT=ewr1.vultrobjects.com"

echo.
echo [*] Guardando configuracion...

:: Write .env file
(
echo # Lab Dashboard Environment Configuration
echo # Generated by configure-storage.bat
echo.
echo VULTR_ACCESS_KEY=%VULTR_ACCESS_KEY%
echo VULTR_SECRET_KEY=%VULTR_SECRET_KEY%
echo VULTR_BUCKET_NAME=%VULTR_BUCKET_NAME%
echo VULTR_ENDPOINT=%VULTR_ENDPOINT%
) > "%~dp0..\scripts\lab_dashboard\server\.env"

echo.
echo [OK] Configuracion guardada en:
echo     scripts\lab_dashboard\server\.env
echo.
echo Ahora puedes ejecutar START-LAB.bat
echo.

pause
